### ISSUE TITLE
dict undefined

### ISSUE THREAD

**Issue by pdimens** [varnerlab/CHEME-130-eCornell-Repository#1]
The dict you are using here is first defined in the cell that comes after it.

https://github.com/varnerlab/CHEME-130-eCornell-Repository/blob/fc1aa7407a0caf5e07dcdedba975fbcbb57d08cb/courses/CHEME-131/module-1/CHEME-131-Module-1-WorkedExample.ipynb#L189

**Comment by varnerlab** [comment]
Fix checked in on commit 59b6ccd
